version: "3"

services:
  web:
    container_name: equipment-monitoring
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=${PORT}
      - DB_HOST=mongo
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
  mongo:
    container_name: equipment-monitoring-db
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none